### PR TITLE
Stylized student nav

### PR DESCRIPTION
**Pull request by gavinksong**

### CODE REVIEW

**Review by emilioaurea — COMMENTED** [review]
Tests are failing. Gasp*

**Comment by gavinksong** [comment]
They're failing because I changed "Speaking" to "Speak" etc.
We should probably be using IDs.

**Comment by yadelab** [comment]
@gavinksong @emilioaurea boys what's the deal for these PRs, are we gonna come to consensus?

**Comment by emilioaurea** [comment]
@gavinksong these pr r still failing

**Comment by emilioaurea** [comment]
this

**Review by emilioaurea — APPROVED** [review]
good work primo

**Pull request merged**
