### PR TITLE
completed video upload logic

### PR DESCRIPTION
**Pull request by samuelkarani**

### CODE REVIEW

**Comment by yadelab** [comment]
@samuelkarani Nice! out of curiousity, does this work on heroku?

**Comment by samuelkarani** [comment]
@yadelab it works on my end. once its merged ill finish up with mp3 uploads and then test if works on heroku

**Comment by yadelab** [comment]
@samuelkarani Alright let's merge it. I'm sure you know Derrick is grading us only based on Heroku

**Review by yadelab — APPROVED** [review]

**Comment by yadelab** [comment]
Hey @samuelkarani 
seems like "This branch is out-of-date with the base branch". Did you fetch, rebase.

**Comment by samuelkarani** [comment]
@yadel should be fine now

**Comment by samuelkarani** [comment]
merci @yadelab

**Comment by yadelab** [comment]
de rien

**Pull request merged**
