### PR TITLE
Email validation bug

### PR DESCRIPTION
**Pull request by samuelkarani**
added tests for email validation based in Team 7's review of our app
still not fully complete, but tests added should work fine

### CODE REVIEW

**Comment by samuelkarani** [comment]
This is the link for the completing story: https://www.pivotaltracker.com/story/show/134633217

**Comment by emilioaurea** [comment]
don't forget to delete branch

**Comment by samuelkarani** [comment]
okay emilio

**Comment by emilioaurea** [comment]
sorry thought pull request was merged

**Review by emilioaurea — APPROVED** [review]
looks good bro.

**Comment by samuelkarani** [comment]
thanks emilio!

**Pull request merged**
