### PR TITLE
deleted admin files

### PR DESCRIPTION
**Pull request by samuelkarani**

### CODE REVIEW

**Comment by emilioaurea** [comment]
Sam, why are we deleting Admin login features for cucumber? Won't we need the "Given an admin exists" to test admin uploads?

**Comment by emilioaurea** [comment]
I meant admin login for step definitions.

**Comment by emilioaurea** [comment]
Ok i see. Login was done through an admin sign in. And "given an admin exists" required the use of an admin model that we don't have.
However, consider this:

one of our user stories this iteration is admin privledges and one of the tasks is admin should be able to log in. Would this not require an admin login cucumber scenario?

This is your user story and I see you adding back some of these files today for iter3-1 as updated cucumber scenarios.

Would like to hear your or anyone else's thoughts.

**Comment by samuelkarani** [comment]
yes you are right. at the time of authoring this, we hadn't decided that we will be doing the admin story for this iteration. i was deleted it to avoid any confusion when someone would think that there is an admin feature, but there actually wasnt.

**Pull request closed without merging**
