### PR TITLE
only one admin

### PR DESCRIPTION
**Pull request by samuelkarani**

### CODE REVIEW

**Comment by yadelab** [comment]
@samuelkarani  having removed  `:registerable` would new students and mentors be able to sign up. Also in the long term, to avoid exposing the Admin credential, we should add it to a gitignore file or something. What do you say?

**Comment by samuelkarani** [comment]
thats for admins and thats precisely why users will not be able to register as admins

**Comment by yadelab** [comment]
Ah . I see. Cool

**Review by yadelab — APPROVED** [review]
lgtm

**Pull request merged**
