### PR TITLE
Listen lesson

### PR DESCRIPTION
**Pull request by KseniiaRyuma**

### CODE REVIEW

**Comment by samuelkarani** [comment]
@KseniiaRyuma  can you git rebase master. somehow your PR branch became outdated. ps: make sure your master is updated (git pull in master)

**Comment by samuelkarani** [comment]
after rebasing, you may have to do a force push (g push origin <branch_name> -f)

**Comment by gavinksong** [comment]
Don't click "update branch"; it creates a merge commit. Sam created one just now. Don't accept this PR until it's gone.

**Comment by gavinksong** [comment]
Also, plz have more descriptive commit messages, and if you can help it, don't have multiple commits modifying the same code over and over in the same PR.

**Comment by gavinksong** [comment]
And also important, don't have junk files like /uploads/sampletext.txt or whatever.

**Pull request closed without merging**
