### PR TITLE
Bootstrap alerts for flash notifications.

### PR DESCRIPTION
**Pull request by gavinksong**
If you're going to use bootstrap, use it properly.

### CODE REVIEW

**Comment by emilioaurea** [comment]
We set the flash value to different bootstrap classes such as success, alert, info, danger. This is why we do the #{key} thing.

**Comment by gavinksong** [comment]
We've been setting flash notifications to flash[:notice] and flash[:alert], neither of which are bootstrap alert classes.

**Comment by gavinksong** [comment]
If you're going to start setting flash[:success], flash[:alert], etc (although I don't think the code should be so tightly coupled with Bootstrap CSS), change the code where we used to set to flash[:notice] and flash[:alert].

**Comment by emilioaurea** [comment]
We did.

**Comment by emilioaurea** [comment]
You are free to propose an alternative scheme. We just wanted to make notifications nicer and make our UI over cooler. Did you see city dog share? we gotta step up our game primo.

**Comment by gavinksong** [comment]
If you've changed everything, then Devise is still setting all of their notifications to notice and alert.

**Comment by gavinksong** [comment]
Because on Heroku, when you sign in or enter incorrect credentials, etc, you get plain ass text.

**Comment by emilioaurea** [comment]
Yea we noticed that. I think we will need a different idea.

**Comment by emilioaurea** [comment]
like four content tags like you were doing.

**Comment by gavinksong** [comment]
Follow convention. Use notify and alert. Where do you use flash messages? I'll change them back.

**Comment by emilioaurea** [comment]
here is the commit 6f5639fed704b8c1263920c475a9fc8ebbd7c80d

**Comment by samuelkarani** [comment]
calm down @gavinksong. overall this is a better visual feedback for the customer i.e. using blue, green or red for visual feedback. Devise will just load as it does because it seems there's no way to integrate with bootstrap. I am closing this PR, it is failing.

**Comment by gavinksong** [comment]
Sam, i dont't think you understand what's happening here.

**Comment by gavinksong** [comment]
Okay. So here's what's happening. I'm also using Bootstrap alerts for notifications, so you get the "visual feedback" you so desire. Right now, Emilio has it so that the app is writing to flash[:warning] or flash[:info] for notifications, and the alerts are being rendered with class "alert alert-#{key}", where key is the flash key. Aside from being really bad practice to _couple CSS with controller logic_, this isn't adherent to the rails convention where notifications are written to flash[:notice] and flash[:alert]. It's not that Devise can't integrate with _Bootstrap_ (which isn't even true at all); it's that Devise is following Rails convention, and we are not. The reason this build is failing is because Emilio's flash notifications aren't being rendered because I'm _not rendering them_ because they are using CSS class names are keys.

**Comment by emilioaurea** [comment]
@samuelkarani was good.

**Comment by gavinksong** [comment]
What the hell

**Pull request closed without merging**
