### PR TITLE
About page

### PR DESCRIPTION
**Pull request by yadelab**

### CODE REVIEW

**Comment by emilioaurea** [comment]
@yadelab you have a merge commit. i think this will give trouble in the future. not sure

**Review by emilioaurea — DISMISSED** [review]
i want to see if can rebase cleanly.

**Comment by yadelab** [comment]
What did the dummy review say?

**Comment by emilioaurea** [comment]
I wanted to see if it could rebase cleanly which was yes.

**Comment by emilioaurea** [comment]
You need tests. The href about isnt a route.

**Comment by emilioaurea** [comment]
screen shot 2016-11-30 at 3 19 59 pm

**Comment by yadelab** [comment]
It's about/Index.

**Comment by emilioaurea** [comment]
i clicked on about tab

**Comment by emilioaurea** [comment]
about/index also fails in url....weird it should be about/index

**Comment by emilioaurea** [comment]
no controller. that's the error

**Comment by emilioaurea** [comment]
Primo. I think your commits aren't what you expect them to be. I am going to go with Sam and Kseniia's about page.

**Pull request closed without merging**
